name: GitHub-Profile-Summary-Cards

on:
  schedule:
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  github-profile-summary-cards:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          UTC_OFFSET: 9
